[project]
name = "mathsagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "mcp[cli]>=1.13.0",
    "ollama>=0.5.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
